#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [ ! -L $HOME/.zshenv ]; then
    ln -s $DOTFILES/zsh/.zshenv $HOME/.zshenv
fi

rm -rf $HOME/.config/zsh
mkdir -p $HOME/.cache/zsh
ln -s $DOTFILES/zsh/config $HOME/.config/zsh

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/conky
ln -s $DOTFILES/conky $HOME/.config/conky

rm -rf $HOME/.config/newsboat
ln -s $DOTFILES/newsboat $HOME/.config/newsboat

rm -rf $HOME/.config/tmux/tmux.conf
rm -rf $HOME/.config/tmux/.tmux-cht-languages
rm -rf $HOME/.config/tmux/.tmux-cht-commands
mkdir -p $HOME/.config/tmux/plugins
ln -s $DOTFILES/tmux/tmux.conf $HOME/.config/tmux/tmux.conf
ln -s $DOTFILES/tmux/.tmux-cht-languages $HOME/.config/tmux/.tmux-cht-languages
ln -s $DOTFILES/tmux/.tmux-cht-commands $HOME/.config/tmux/.tmux-cht-commands

if [[ ! -d $HOME/.config/tmux/plugins/tpm ]]; then
	git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
fi

rm -rf $HOME/.local/bin
ln -s $DOTFILES/scripts $HOME/.local/bin

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

rm -rf $HOME/.config/bat
ln -s $DOTFILES/bat $HOME/.config/bat

# Sensitive things get put in here, so only copy, no symlink
mkdir -p $HOME/.config/gnupg
cp $DOTFILES/gnupg/gpg-agent.conf $HOME/.config/gnupg/gpg-agent.conf

# Create notes dir
mkdir -p $HOME/Documents/Notes

# Default global prettier config for use
# with prettierd in neovim by setting
# $PRETTIERD_DEFAULT_CONFIG env var
rm -rf $HOME/.config/prettier
ln -s $DOTFILES/prettier $HOME/.config/prettier

# Projects dir
mkdir -p $HOME/Projects
if [[ ! -L $HOME/Projects/.editorconfig ]]; then
	ln -s $DOTFILES/.editorconfig $HOME/Projects/.editorconfig
fi
