#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/conky/conky.conf
ln -s $DOTFILES/conky/conky.conf $HOME/.config/conky/conky.conf

rm -rf $HOME/.config/newsboat
ln -s $DOTFILES/newsboat $HOME/.config/newsboat

mkdir -p $HOME/.config/tmux
rm -rf $HOME/.config/tmux/tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.config/tmux/tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
