#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [ ! -L $HOME/.zshenv ]; then
    ln -s $DOTFILES/zsh/.zshenv $HOME/.zshenv
fi

rm -rf $HOME/.config/zsh
mkdir -p $ZSH_CACHE_DIR
ln -s $DOTFILES/zsh/config $HOME/.config/zsh

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/conky
ln -s $DOTFILES/conky $HOME/.config/conky

rm -rf $HOME/.config/newsboat
ln -s $DOTFILES/newsboat $HOME/.config/newsboat

mkdir -p $HOME/.config/tmux
rm -rf $HOME/.config/tmux/tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.config/tmux/tmux.conf

mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

# Sensitive things get put in here, so only copy, no symlink
mkdir -p $HOME/.config/gnupg
cp ./gnupg/gpg-agent.conf $HOME/.config/gnupg/gpg-agent.conf
