#!/usr/bin/env bash

# A simple, if maybe hacky way, to ensure it only runs once
pidof hyprpaper || hyprpaper &

WALL=$(fd --type f . ~/Pictures/Wallpapers/ | shuf -n 1)

hyprctl hyprpaper unload all
hyprctl hyprpaper preload $WALL

for monitor in $(hyprctl monitors | grep "Monitor" | awk '{ print $2 }'); do
	hyprctl hyprpaper wallpaper "$monitor,$WALL"
done

