import = ["/home/alice/.config/alacritty/themes/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Monaspace Radon"
style = "Bold"

[font.bold_italic]
family = "Monaspace Radon"
style = "BoldItalic"

[font.italic]
family = "Monaspace Radon"
style = "Italic"

[font.normal]
family = "Monaspace Radon"
style = "Regular"

[font.offset]
y = 8

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 1

[window.padding]
x = 5
# y = 5
